// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleERP.Document.API.Infrastructure.Data;

namespace SimpleERP.Document.API.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.DocumentInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Creator");

                    b.Property<string>("DateOfCreate");

                    b.Property<string>("DateOfModify");

                    b.Property<string>("DateOfRelease");

                    b.Property<long>("DomainId");

                    b.Property<string>("FilePath");

                    b.Property<long>("IssuerId");

                    b.Property<string>("Modifier");

                    b.Property<string>("No");

                    b.Property<string>("Subject");

                    b.Property<string>("Text");

                    b.Property<long>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("IssuerId");

                    b.HasIndex("TypeId");

                    b.ToTable("DocumentInfos");
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.Domain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Hidden");

                    b.Property<bool>("Readonly");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hidden = false,
                            Readonly = true,
                            Title = "اداری"
                        },
                        new
                        {
                            Id = 2L,
                            Hidden = false,
                            Readonly = true,
                            Title = "مالی"
                        },
                        new
                        {
                            Id = 3L,
                            Hidden = false,
                            Readonly = true,
                            Title = "فناوری اطلاعات"
                        },
                        new
                        {
                            Id = 4L,
                            Hidden = false,
                            Readonly = true,
                            Title = "فنی"
                        });
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.Issuer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Hidden");

                    b.Property<bool>("Readonly");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Issuers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hidden = false,
                            Readonly = true,
                            Title = "سازمان برنامه و بودجه"
                        },
                        new
                        {
                            Id = 2L,
                            Hidden = false,
                            Readonly = true,
                            Title = "سازمان نظام مهندسی"
                        },
                        new
                        {
                            Id = 3L,
                            Hidden = false,
                            Readonly = true,
                            Title = "وزارت راه و شهرسازی"
                        },
                        new
                        {
                            Id = 4L,
                            Hidden = false,
                            Readonly = true,
                            Title = "سازمان اداری و استخدامی"
                        },
                        new
                        {
                            Id = 5L,
                            Hidden = false,
                            Readonly = true,
                            Title = "وزارت اقتصاد و دارایی"
                        },
                        new
                        {
                            Id = 6L,
                            Hidden = false,
                            Readonly = true,
                            Title = "هیأت دولت"
                        },
                        new
                        {
                            Id = 7L,
                            Hidden = false,
                            Readonly = true,
                            Title = "قانون مصوب"
                        });
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.Type", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Hidden");

                    b.Property<bool>("Readonly");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hidden = false,
                            Readonly = true,
                            Title = "آئین‌نامه"
                        },
                        new
                        {
                            Id = 2L,
                            Hidden = false,
                            Readonly = true,
                            Title = "بخشنامه"
                        },
                        new
                        {
                            Id = 3L,
                            Hidden = false,
                            Readonly = true,
                            Title = "دستورالعمل"
                        });
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.DocumentInfo", b =>
                {
                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.Domain", "Domain")
                        .WithMany("DocumentInfos")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.Issuer", "Issuer")
                        .WithMany("DocumentInfos")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.Type", "Type")
                        .WithMany("DocumentInfos")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
