// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleERP.Document.API.Infrastructure.Data;

namespace SimpleERP.Document.API.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.DocumentFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DocumentInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentInfoId");

                    b.ToTable("DocumentFile");
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.DocumentInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfCreate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfModify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfRelease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DomainId")
                        .HasColumnType("bigint");

                    b.Property<long>("IssuerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("IssuerId");

                    b.HasIndex("TypeId");

                    b.ToTable("DocumentInfos");
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.Domain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<bool>("Readonly")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hidden = false,
                            Readonly = true,
                            Title = "اداری"
                        },
                        new
                        {
                            Id = 2L,
                            Hidden = false,
                            Readonly = true,
                            Title = "مالی"
                        },
                        new
                        {
                            Id = 3L,
                            Hidden = false,
                            Readonly = true,
                            Title = "فناوری اطلاعات"
                        },
                        new
                        {
                            Id = 4L,
                            Hidden = false,
                            Readonly = true,
                            Title = "فنی"
                        });
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.Issuer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<bool>("Readonly")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issuers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hidden = false,
                            Readonly = true,
                            Title = "سازمان برنامه و بودجه"
                        },
                        new
                        {
                            Id = 2L,
                            Hidden = false,
                            Readonly = true,
                            Title = "سازمان نظام مهندسی"
                        },
                        new
                        {
                            Id = 3L,
                            Hidden = false,
                            Readonly = true,
                            Title = "وزارت راه و شهرسازی"
                        },
                        new
                        {
                            Id = 4L,
                            Hidden = false,
                            Readonly = true,
                            Title = "سازمان اداری و استخدامی"
                        },
                        new
                        {
                            Id = 5L,
                            Hidden = false,
                            Readonly = true,
                            Title = "وزارت اقتصاد و دارایی"
                        },
                        new
                        {
                            Id = 6L,
                            Hidden = false,
                            Readonly = true,
                            Title = "هیأت دولت"
                        },
                        new
                        {
                            Id = 7L,
                            Hidden = false,
                            Readonly = true,
                            Title = "قانون مصوب"
                        });
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.Type", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<bool>("Readonly")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Hidden = false,
                            Readonly = true,
                            Title = "آئین‌نامه"
                        },
                        new
                        {
                            Id = 2L,
                            Hidden = false,
                            Readonly = true,
                            Title = "بخشنامه"
                        },
                        new
                        {
                            Id = 3L,
                            Hidden = false,
                            Readonly = true,
                            Title = "دستورالعمل"
                        });
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.DocumentFile", b =>
                {
                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.DocumentInfo", null)
                        .WithMany("DocumentFiles")
                        .HasForeignKey("DocumentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleERP.Document.API.Infrastructure.Data.DocumentInfo", b =>
                {
                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.Domain", "Domain")
                        .WithMany("DocumentInfos")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.Issuer", "Issuer")
                        .WithMany("DocumentInfos")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleERP.Document.API.Infrastructure.Data.Type", "Type")
                        .WithMany("DocumentInfos")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
